### ISSUE TITLE
Let users custom execute instructions.

### ISSUE THREAD

**Issue by openingnow** [mattn/vscode-runner#11]
Things in [defaultlanguagemap](https://github.com/mattn/vscode-runner/blob/master/src/extension.ts#L13) would be moved into runner.languageMap with supporting some special chracters like % (as in vim) or [Variable substitution](https://code.visualstudio.com/Docs/editor/tasks#_variable-substitution) like ${file}...etc to achieve several benefits.
First, by doing so we can support compiled languages. I tried to use this extension for C without modifying but soon realized It is impossible. For example, `gcc /path/to/source.c -o /tmp/a.out.vscode && /tmp/a.out.vscode` can't made by configuring runner.XXXMap. Also showing them in `settings.json` can give users hint how to fill `runner.XXXmap`.

For example, `php: "php"` in `defaultlanguagemap` can be changed to `php: "php %"` or `php: "php ${file}"`in `runner.languageMap`. Maybe supporting `%` is enough.

**Comment by mattn** [comment]
too late, but added `$(file)`.
