### ISSUE TITLE
Stop the endless script

### ISSUE THREAD

**Issue by ghost** [mattn/vscode-runner#12]
If the script is endless description, it is impossible to stop the calculation. perhaps worth adding stop the timer and hotKey stop.

**Comment by mattn** [comment]
which way do you prefer?

**Comment by ghost** [comment]
if replace the "сhild" from async to the synchronous stream, and set the timer for 1-3 seconds. the VSCode will not throw hang. But my knowledge of the VSCode architecture and programming JS does not exist for this task/
