### ISSUE TITLE
Make it possible to "ctrl-c" a script!

### ISSUE THREAD

**Issue by oderwat** [mattn/vscode-runner#13]
I hope you can make it possible that one can bind ctrl+c to a runner command which sends the corresponding signal to a runner!

It would also be nice to be able to have just one output windows instead of one for every file the runner is used with (esp. because I do not see a way to close them).

**Comment by mattn** [comment]
AFAIK, vscode doesn't provide way to handle keys specific per output channel.

**Comment by oderwat** [comment]
The key could be pressed in the editor! This is afaik how the atom "script" runner handles it. Just have a command which sends the signal to the running task associated with the editor window and that gets bound to "ctrl+c" or any other combination the user wants.

**Comment by mattn** [comment]
atom-runner seems register the key in global scope.

https://github.com/lsegal/atom-runner/blob/master/keymaps/atom-runner.cson#L24-L25

**Comment by oderwat** [comment]
OK. But it also has just one global runner. In your implementation every file has his own "output" window. Can't you just remember (or identify) the pid for a source file that was run and create an action for the editor to send the signal to the corresponding pid (if still valid...)?

**Comment by oderwat** [comment]
BTW.. I don't refer to "atom-runner" but "[atom-script](https://github.com/rgbkrk/atom-script)" which has much more options.

**Comment by oderwat** [comment]
Works "kinda" but not how I expected it.

I believe that his should better use SIGINT (thats what CTRL+C sends) instead of SIGTERM (the default of kill <pid>).

**Comment by mattn** [comment]
done, but currently I can't check the behavior on UNIX OSs.
