### ISSUE TITLE
File name/path with spaces are not recognized by some interpreters

### ISSUE THREAD

**Issue by emredjan** [mattn/vscode-runner#15]
If there are spaces in the filename while using runner, the interpreter (at least Rscript, will test others) do not understand the command: 

![image](https://cloud.githubusercontent.com/assets/389091/15057481/435ee642-1317-11e6-8ae9-b2565acbedc9.png)

Seems can be fixed by adding quote characters around the `fileName` calls:

``` Javascript
'\"' + fileName + '\"'
```

**Comment by mattn** [comment]
closed by https://github.com/mattn/vscode-runner/pull/16
