### ISSUE TITLE
No feedback on successful completion any more

### ISSUE THREAD

**Issue by kAlvaro** [mattn/vscode-runner#26]
Since version 1.27 I no longer see any feedback upon completion successful, at least when running PHP scripts. There's no way to know if the script has finished or it's still running:

![Running PHP script](https://i.imgur.com/jBnDgeU.gif)

It's only an issue on success; on error I still see:

> Exited with status 255

It's probably a change in Visual Studio Code since it used to work fine and the extension has not been updated recently.

**Comment by mattn** [comment]
I seems not implement displaying mesages on succeeded.

https://github.com/mattn/vscode-runner/blob/c1b17dbfe4fcde41649916bd98dc0d97514389fd/src/extension.ts#L133-L134

okay, I'll look into it in later. Thank you.

**Comment by kAlvaro** [comment]
I'm confused... I've finally managed to try earlier versions of Visual Studio Code and there's no feedback either—and the extension has not been updated in two years. I wonder if it's just a serious case of false memory on my side...

In such case, you might consider this a feature request. Sorry!

**Comment by mattn** [comment]
Now I releated 0.15 that fixes this issue. Thank you.
