### ISSUE TITLE
Please give some more examples

### ISSUE THREAD

**Issue by haichen** [mattn/vscode-runner#8]
I tried to add C:\Program Files\AutoHotkey\AutoHotkey.exe
The script extension is .ahk

I tried to add something (and a few more) like this to settings.json but without success.
"runner.languageMap": {"autohotkey": "autohotkey"},
 "runner.extensionMap": { "ahk": "autohotkey"},

Could you please help me?

**Comment by haichen** [comment]
I reinstalled everything and now this settings.js are working
{
    "runner.languageMap": {"autohotkey": "C:/Program Files/AutoHotkey/autohotkey.exe"},
    "runner.extensionMap": { "ahk": "autohotkey"},
}
Thought i tried this..

**Comment by mattn** [comment]
this is closable?

**Comment by haichen** [comment]
Yes and thank you very much for your extension!
A happy new 2016 and best wishes from me

**Comment by mattn** [comment]
you too :smile:
